---
- name: Fzf - Exists
  ansible.builtin.stat:
    path: ~/.fzf/bin/fzf
  register: fzf_exists_result

- name: Checkout Fzf installer
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest:  ~/.fzf/

- name: Fzf - Install
  ansible.builtin.shell: >
    ~/.fzf/install --xdg --all --no-update-rc
  when: fzf_exists_result.stat.exists == false # or upgrade == true
