---
- name: Packer - Exists
  stat:
    path: /usr/bin/packer
  register: packer_exists_result

- block:
    - name: Packer - Get HashiCorp gpg
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Packer - Add repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Packer - Install/Upgrade
      apt:
        update_cache: true
        pkg:
          - packer
  when: packer_exists_result.stat.exists == false or upgrade == true
