- name: Packer - Get HashiCorp gpg
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Packer - Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Packer - Install/Upgrade
  apt:
    update_cache: yes
    pkg:
      - packer