---
- name: Slack - Exists
  stat:
    path: /usr/bin/slack
  register: slack_result

- name: Slack
  community.general.snap:
    name: slack
    classic: yes
  when: slack_result.stat.exists == False or upgrade == true
