---
- name: Install system packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: latest
    update_cache: yes

- name: Install pip modules
  pip:
    name: "{{ pip_packages }}"
