- name: Virtualbox signing key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Virtualbox Repository
  apt:
    deb: "https://download.virtualbox.org/virtualbox/6.1.16/{{ virtualbox_version_deb }}"
    state: present

- name: Virtualbox Install
  apt:
    update_cache: yes
    pkg:
      - virtualbox-6.1