---
- name: Connectus-Base
  hosts: all
  become: yes
  remote_user: ubuntu
  vars:
    upgrade: true
    debug: true
    git_keys:
      - /home/kedwards/.ssh/kedwards/id_rsa
      - /home/kedwards/.ssh/kedwards/id_rsa.pub
    git_token: f2f8b2260ee6d53264bfed8c62d79b7cff10dcb1
    git_organization: connectusglobal
    git_repo_name: rtls-meta
    docker_login_username: kevinedwards
    docker_login_password: Y2tFT9n*xEqb
    docker_private_registry_url: registry.gitlab.com/sewio/studio/rtls-studio
    docker_private_login_username: ConnectusServicesLtd
    docker_private_login_password: daz-9TgZmqehQVW7sX1w
  roles:
    - sysinit
    - sewio
