---
- name: System Initialization
  hosts: "{{ host | default('localhost') }}"
  become: true
  gather_facts: true
  vars:
    upgrade: true
    github_token: "{{ lookup('community.general.onepassword', 'github-pat', field='credential') }}"
  roles:
    - sysinit
