---
- name: Connectus-RTLS-Base
  hosts: all
  become: true
  remote_user: ubuntu
  vars:
    upgrade: true
    debug: true
    git_repo_name: rtls-meta
    docker_login_username: kevinedwards
    docker_login_password: Y2tFT9n*xEqb
    docker_private_registry_url: registry.gitlab.com/sewio/studio/rtls-studio
    docker_private_login_username: ConnectusServicesLtd
    docker_private_login_password: daz-9TgZmqehQVW7sX1w
  roles:
    - sysinit
    - sewio
