---
- name: Dropbox - Exists
  ansible.builtin.stat:
    path: /usr/bin/dropbox
  register: dropbox_exists_result

- name: Dropbox - Install/Upgrade
  ansible.builtin.apt:
    deb: https://www.dropbox.com/download?dl=packages/debian/dropbox_2024.01.22_amd64.deb
  when: dropbox_exists_result.stat.exists == false or upgrade == true
