---
- block:
    - name: Mise - Exists
      ansible.builtin.stat:
        path: "/home/{{ lookup('env','USER') }}/.local/bin/mise"
      register: mise_exists_result

    - name: Mise - Create bin direcitory
      ansible.builtin.file:
        path: "/home/{{ lookup('env','USER') }}/.local/bin"
        state: directory

    - name: Mise - Install/Upgrade
      ansible.builtin.get_url:
        url: https://mise.jdx.dev/mise-latest-linux-x64
        dest: "/home/{{ lookup('env','USER') }}/.local/bin/mise"
        mode: +x
      when: mise_exists_result.stat.exists == false or upgrade == true

    - name: Mise - set binary
      ansible.builtin.set_fact:
        mise_bin: "/home/{{ lookup('env','USER') }}/.local/bin/mise"
  become_user: "{{ lookup('env','USER') }}"   
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
    - name: Mise - Exists
      ansible.builtin.stat:
        path: "/usr/bin/mise"
      register: mise_exists_result

    - name: Mise - set binary
      ansible.builtin.set_fact:
        mise_bin: "/usr/bin/mise"
      when: mise_exists_result.stat.exists == false or upgrade == true
  become_user: "{{ lookup('env','USER') }}"   
  when: ansible_distribution == 'Archlinux'

- name: Mise - Install/Upgrade
  block:
    - name: Mise - Install Plugins
      ansible.builtin.shell: >
        {{ mise_bin }} plugin add {{ plugin_item.plugin }} {{ plugin_item.src }}
      loop_control:
        loop_var: plugin_item
      loop: "{{ mise_custom_plugins }}"

    - name: Mise - Install Plugins
      ansible.builtin.shell: >
        if [ ! -d "$HOME/.local/share/mise/plugins/{{ plugin_item }}" ]; then
          {{ mise_bin }} use -g -y {{ plugin_item }}
        fi
      loop_control:
        loop_var: plugin_item
      loop: "{{ mise_plugins }}"
  become_user: "{{ lookup('env','USER') }}"
  when: mise_bin
