---
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - gnupg-agent
  - golang-go
  - libnss3-tools
  - lsb-release
  - make
  - meld
  - unzip
  - vim-nox
  - xsel

pip_packages:
  - github3.py
  - botocore
  - boto3
