---
- name: Asdf - Exists
  ansible.builtin.stat:
    path: "/home/{{ lookup('env','USER') }}/.asdf"
  register: asdf_exists_result

- name: Asdf - Install/Upgrade
  block:
    - name: Asdf - Install/Upgrade
      ansible.builtin.git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "/home/{{ lookup('env','USER') }}/.asdf"
        version: v0.14.0
    
    - name: Asdf - Install Plugins
      ansible.builtin.shell: >
        /home/{{ lookup('env','USER') }}/.asdf/bin/asdf plugin-add {{ item }} &&
        /home/{{ lookup('env','USER') }}/.asdf/bin/asdf install {{ item }} latest &&
        /home/{{ lookup('env','USER') }}/.asdf/bin/asdf global {{ item }} latest
      loop:
        - awscli
        - direnv
        - eksctl
        - fzf
        - github-cli
        - golang
        - granted
        - kubectl
        - minikube
        - neovim
        - nodejs
        - python
        - ripgrep
  become: true
  become_user: "{{ lookup('env','USER') }}"
  when: asdf_exists_result.stat.exists == false or upgrade == true
    	
