---
- name: Check for docker gpg file
  ansible.builtin.stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_gpg

- name: "Add docker offical GPG key for {{ ansible_distribution }}"
  ansible.builtin.shell: >
     curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  when: not docker_gpg.stat.exists

- name: Touch the same file, but add/remove some permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: a+r

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} stable"
    state: present

- name: Docker - Install
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Docker - Add docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker User
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop:
    - "{{ lookup('env','USER') }}"
