---
- name: Install docker python modules
  pip:
    name:
      - docker
      - docker-compose

- name: Install system packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: latest
    update_cache: yes

- name: Ensure required studio files & folders are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: preserve
    owner: ubuntu
    group: ubuntu
  loop: "{{ copy_files }}"

- name: Log into DockerHub
  community.general.docker_login:
    username: "{{ docker_login_username }}"
    password: "{{ docker_login_password }}"

- name: Log into private registry
  community.general.docker_login:
    registry_url: "{{  docker_private_registry_url }}"
    username: "{{ docker_private_login_username }}"
    password: "{{ docker_private_login_password }}"

- name: Start services, pulling images (updates)
  community.docker.docker_compose:
    project_src: /home/ubuntu
    pull: yes
    state: present
