---
- name: Neovim - Exists
  ansible.builtin.stat:
    path: /usr/local/bin/nvim
  register: nvim_exists_result

- name: Neovim - Install
  block:
    - name: Neovim - Install
      ansible.builtin.unarchive:
        src: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
        dest: /usr/local
        remote_src: yes

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /usr/local/nvim-linux64/bin/nvim
        dest: /usr/local/bin/nvim
        state: link
  when: nvim_exists_result.stat.exists == false or upgrade == true
