---
packages:
  - amazon-ecr-credential-helper
  - apt-transport-https
  - curl
  # - python3-botocore
  # - python3-boto3
  - build-essential
  # - ca-certificates
  # - curl
  # - firefox
  # - gnupg
  # - gnupg-agent
  # - golang-go
  - libffi-dev
  # - libnss3-tools
  - libbz2-dev
  - liblzma-dev
  - libncursesw5-dev
  - libreadline-dev
  - libssl-dev
  - libsqlite3-dev
  - libxml2-dev
  - libxmlsec1-dev
  # - llvm
  # - lsb-release
  # - make
  # - meld
  # - python3-venv
  - tk-dev
  # - unzip
  # - vim-nox
  # - wget --
  # - xsel
  - xz-utils
  - zlib1g-dev
# Setting up python3-wrapt (1.14.1-2+b2) ...
# Setting up python3-deprecated (1.2.13-3) ...
# Setting up python3-github (1.55-3) ...

