---
packages:
  - amazon-ecr-credential-helper
  - apt-transport-https
  - curl
  - build-essential
  - ca-certificates
  - libffi-dev
  - libnss3-tools
  - libbz2-dev
  - liblzma-dev
  - libncursesw5-dev
  - libreadline-dev
  - libssl-dev
  - libsqlite3-dev
  - libxml2-dev
  - libxmlsec1-dev
  - make
  - tk-dev
  - xsel
  - xz-utils
  - zlib1g-dev
  - thinkfan

system_tools:
  - aws 
  - docker
  - dropbox
  - mise
  - opass
  - starship
  - thinkfan

mise_plugins:
  - awscli
  - direnv
  - eksctl
  - fzf
  - github-cli
  - granted
  - kubectl
  - minikube
  - neovim
  - ripgrep
  - uv
  - git-worktree-wrapper
  # - golang, nodejs, python  # default plugins

mise_custom_plugins:
  - { plugin: "git-worktree-wrapper", src: "https://github.com/kedwards/asdf-git-worktree-wrapper.git" }
