---
packages:
  - vim-nox
  # - nautilus-dropbox
  - apt-transport-https
  - curl
  - gnupg2
  - gnupg-agent
  - python3-pip

pip_packages:
  - github3.py
  - boto3
  - botocore

virtualbox_version_deb: virtualbox-6.1_6.1.16-140961~Ubuntu~eoan_amd64.deb

git_lfs_repos:
  - "deb https://packagecloud.io/github/git-lfs/ubuntu/ focal main"
  - "deb-src https://packagecloud.io/github/git-lfs/ubuntu/ focal main"
