---
- name: include os vars
  include_vars: "{{ ansible_distribution }}.yml"

- import_tasks: debug.yml
  when: debug == "true"

- import_tasks: deps.yml

- import_tasks: module/atlantis.yml
  tags:
    - atlantis

- import_tasks: module/aws-cli.yml
  tags:
    - aws-cli
    - aws
    - req

- import_tasks: module/aws-vault.yml
  tags:
    - aws-vault
    - aws
    - req

- import_tasks: module/docker.yml
  tags:
    - docker
    - docker-compose
    - docker-machine
    - req

- import_tasks: module/docker-compose.yml
  tags:
    - docker-compose
    - req

- import_tasks: module/dropbox.yml
  tags:
    - dropbox
    - req

- import_tasks: module/git-filter-repo.yml
  tags:
    - git-filter-repo

- import_tasks: module/git-lfs.yml
  tags:
    - git-lfs

- import_tasks: module/golang.yml
  tags:
    - golang

- import_tasks: module/kubectl.yml
  tags:
    - kubectl
    - minikube

- import_tasks: module/minikube.yml
  tags:
    - minikube

- import_tasks: module/mkcert.yml
  tags:
    - mkcert

- import_tasks: module/ngrok.yml
  tags:
    - atlantis
    - ngrok

- import_tasks: module/packer.yml
  tags:
    - packer
    - req

- import_tasks: module/postman.yml
  tags:
    - postman
    - req

- import_tasks: module/skype.yml
  tags:
    - skype
    - comms

- import_tasks: module/slack.yml
  tags:
    - slack
    - comms

- import_tasks: module/teams.yml
  tags:
    - teams
    - comms

- import_tasks: module/teamviewer.yml
  tags:
    - comms
    - teamviewer

- import_tasks: module/terraform.yml
  tags:
    - terraform
    - terraspace
    - terragrunt
    - terrascan
    - req

- import_tasks: module/terragrunt.yml
  tags:
    - terragrunt

- import_tasks: module/terrascan.yml
  tags:
    - terrascan

- import_tasks: module/terraspace.yml
  tags:
    - terraspace

- import_tasks: module/tor-browser.yml
  tags:
    - tor

- import_tasks: module/vagrant.yml
  tags:
    - vagrant
    - virtualbox
    - req

- import_tasks: module/virtualbox.yml
  tags:
    - virtualbox
    - req

- import_tasks: module/vscode.yml
  tags:
    - vscode
    - req

- import_tasks: module/zoom.yml
  tags:
    - zoom
    - comms
