---
- name: System info
  ansible.builtin.debug:
    msg: |
      User: "{{ ansible_user_id }}"
      Sudo User: "{{ lookup('env','USER') }}"
      System: "{{ ansible_system }}"
      Architecture: "{{ ansible_userspace_architecture }}"
      Distribution: "{{ ansible_distribution }}"
      Release: "{{ ansible_distribution_release }}"
      
- name: Install system packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Install required system tools
  ansible.builtin.include_tasks: tasks/{{ item }}.yml
  loop: "{{ system_tools }}"

- name: Applications
  ansible.builtin.include_tasks: "tasks/{{ item  }}.yml"
  loop: "{{ apps }}"
  when: apps is defined
