---
- name: System info
  ansible.builtin.debug:
    msg: |
      User: "{{ ansible_user_id }}"
      Sudo User: "{{ lookup('env','USER') }}"
      System: "{{ ansible_system }}"
      Architecture: "{{ ansible_userspace_architecture }}"
      Distribution: "{{ ansible_distribution }}"
      Release: "{{ ansible_distribution_release }}"

- name: Load variables
  ansible.builtin.include_vars: "{{ansible_distribution}}.yml"

- name: Install system packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  when: ansible_distribution == 'Debian'

- name: Install system packages
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  when: ansible_distribution == 'Archlinux'

- name: Install required system tools
  ansible.builtin.include_tasks: "tools/{{ item }}.yml"
  loop: "{{ system_tools }}"
  when: not apps is defined and ansible_distribution == 'Debian'
