---
- name: Install, configure base system
  block:
    - name: Info
      ansible.builtin.debug:
        msg: |
          User: "{{ ansible_user_id }}"
          Sudo User: "{{ lookup('env','USER') }}"
          System: "{{ ansible_system }}"
          Architecture: "{{ ansible_userspace_architecture }}"
          Distribution: "{{ ansible_distribution }}"
          Release: "{{ ansible_distribution_release }}"
          Group: "{{ var_group }}"
          Host: "{{ var_host }}"

    - name: include os vars
      ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

    - name: Add non-free official repository for Debian
      ansible.builtin.apt_repository:
        repo: "deb http://ftp.ca.debian.org/debian/ {{ ansible_distribution_release }} main non-free"
      when: ansible_distribution == "Debian"

    - name: Install system packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present

    - name: Install pip modules
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        state: present
  tags:
    - always

- name: Core tools
  block:
    - name: AWS-Cli
      ansible.builtin.import_tasks: module/aws-cli.yml
      tags:
        - aws-cli

    - name: AWS Vault
      ansible.builtin.import_tasks: module/aws-vault.yml
      tags:
        - aws-vault

    - name: Docker
      ansible.builtin.import_tasks: module/docker.yml
      tags:
        - docker
        - docker-compose

    - name: Dropbox
      ansible.builtin.import_tasks: module/dropbox.yml
      tags:
        - dropbox

    - name: Github Cli
      ansible.builtin.import_tasks: module/github-cli.yml
      tags:
        - github-cli

    - name: Granted
      ansible.builtin.import_tasks: module/granted.yml
      tags:
        - granted

    - name: 1Password
      ansible.builtin.import_tasks: module/opass.yml
      tags:
        - opass

    - ansible.builtin.import_tasks: module/postman.yml
      tags:
        - postman

    - name: SSM Manager
      ansible.builtin.import_tasks: module/ssm-manager-plugin.yml
      tags:
        - ssm-manager-plugin

    - name: VSCode
      ansible.builtin.import_tasks: module/vscode.yml
      tags:
        - vscode
  tags:
    - core

- name: K8s
  block:
    - ansible.builtin.import_tasks: module/eksctl.yml
      tags:
        - eksctl

    - ansible.builtin.import_tasks: module/kubectl.yml
      tags:
        - kubectl

    - ansible.builtin.import_tasks: module/minikube.yml
      tags:
        - minikube
  tags:
    - k8s

- name: Terraform tools
  block:
    - ansible.builtin.import_tasks: module/terraform.yml
      tags:
        - terraform
        - terragrunt

    - ansible.builtin.import_tasks: module/terragrunt.yml
      tags:
        - terraform
  tags:
    - tf

- name: Communications
  block:
    - name: Skype
      ansible.builtin.import_tasks: module/skype.yml
      tags:
        - skype

    - name: Teams
      ansible.builtin.import_tasks: module/teams.yml
      tags:
        - teams

    - name: Teamviewer
      ansible.builtin.import_tasks: module/teamviewer.yml
      tags:
        - teamviewer

    - name: Zoom
      ansible.builtin.import_tasks: module/zoom.yml
      tags:
        - zoom
  tags:
    - comms