---
- name: Install, configure base system
  block:
    - name: System info
      ansible.builtin.debug:
        msg: |
          User: "{{ ansible_user_id }}"
          Sudo User: "{{ lookup('env','USER') }}"
          System: "{{ ansible_system }}"
          Architecture: "{{ ansible_userspace_architecture }}"
          Distribution: "{{ ansible_distribution }}"
          Release: "{{ ansible_distribution_release }}"
          Group: "{{ var_group }}"
          Host: "{{ var_host }}"
          
    - name: Install system packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
  tags:
    - always

- name: System tools
  block:
    - name: mise
      ansible.builtin.include_tasks: system/{{ item }}.yml
      loop:
        - mise
    
    - name: AWS
      ansible.builtin.import_tasks: system/aws.yml
      tags:
        - aws
    
    - name: Docker
      ansible.builtin.import_tasks: system/docker.yml
      tags:
        - docker
        - docker-compose
        - docker-completion

    - name: Dropbox
      ansible.builtin.import_tasks: system/dropbox.yml
      tags:
        - dropbox

    - name: 1Password
      ansible.builtin.import_tasks: system/opass.yml
      tags:
        - opass
    
    - name: Thinkpad fan control
      ansible.builtin.import_tasks: system/thinkfan.yml
      tags:
        - thinkfan
  tags:
    - system

- name: Applications
  ansible.builtin.include_tasks: "apps/{{ item  }}.yml"
  loop: "{{ apps }}"
  when: apps is defined
