---
- name: Install, configure base system
  block:
    - name: Info
      ansible.builtin.debug:
        msg: |
          User: "{{ ansible_user_id }}"
          Sudo User: "{{ lookup('env','USER') }}"
          System: "{{ ansible_system }}"
          Architecture: "{{ ansible_userspace_architecture }}"
          Distribution: "{{ ansible_distribution }}"
          Release: "{{ ansible_distribution_release }}"
          Group: "{{ var_group }}"
          Host: "{{ var_host }}"

    - name: include os vars
      ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

    - name: Add non-free official repository for Debian
      ansible.builtin.apt_repository:
        repo: "deb http://ftp.ca.debian.org/debian/ {{ ansible_distribution_release }} main non-free"
      when: ansible_distribution == "Debian"

    - name: Install system packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
  tags:
    - always

- name: Core tools
  block:
    - name: AWS-Cli
      ansible.builtin.import_tasks: core/aws-cli.yml
      tags:
        - aws-cli

    - name: dbeaver
      ansible.builtin.import_tasks: core/dbeaver.yml
      tags:
        - dbeaver
        
    - name: Docker
      ansible.builtin.import_tasks: core/docker.yml
      tags:
        - docker
        - docker-compose

    - name: Dropbox
      ansible.builtin.import_tasks: core/dropbox.yml
      tags:
        - dropbox

    - name: Github Cli
      ansible.builtin.import_tasks: core/github-cli.yml
      tags:
        - github-cli

    - name: Granted
      ansible.builtin.import_tasks: core/granted.yml
      tags:
        - granted

    - name: 1Password
      ansible.builtin.import_tasks: core/opass.yml
      tags:
        - opass

    - name: SSM Manager
      ansible.builtin.import_tasks: core/ssm-manager-plugin.yml
      tags:
        - ssm-manager-plugin

    - name: VSCode
      ansible.builtin.import_tasks: core/vscode.yml
      tags:
        - vscode
  tags:
    - core

- name: Devops
  block:
    - name: AWS Vault
      ansible.builtin.import_tasks: devops/aws-vault.yml
      tags:
        - aws-vault

    - name: terraform
      ansible.builtin.import_tasks: devops/terraform.yml
      tags:
        - terraform
        - terragrunt

    - name: terragrunt
      ansible.builtin.import_tasks: devops/terragrunt.yml
      tags:
        - terraform
    
    - name: Packer
      ansible.builtin.import_tasks: devops/packer.yml
      tags:
        - packer
    
    - name: Leaap
      ansible.builtin.import_tasks: devops/leapp.yml
      tags:
        - leapp
    
    - name: Mkcert
      ansible.builtin.import_tasks: devops/mkcert.yml
      tags:
        - mkcert
    
    - name: Postman
      ansible.builtin.import_tasks: devops/postman.yml
      tags:
        - postman

    - name: K8s
      block:
        - ansible.builtin.import_tasks: devops/eksctl.yml
          tags:
            - eksctl

        - ansible.builtin.import_tasks: devops/kubectl.yml
          tags:
            - kubectl

        - ansible.builtin.import_tasks: devops/minikube.yml
          tags:
            - minikube
      tags:
        - k8s
  tags:
    - devops

- name: Communications
  block:
    - name: Skype
      ansible.builtin.import_tasks: comms/skype.yml
      tags:
        - skype

    - name: Teams
      ansible.builtin.import_tasks: comms/teams.yml
      tags:
        - teams

    - name: Teamviewer
      ansible.builtin.import_tasks: comms/teamviewer.yml
      tags:
        - teamviewer

    - name: Zoom
      ansible.builtin.import_tasks: comms/zoom.yml
      tags:
        - zoom
  tags:
    - comms