---
- name: Docker - Install
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Docker - Add docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker User
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop:
    - "{{ lookup('env','USER') }}"
