---
- name: Docker - Get signing key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Docker - Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Docker - Install
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true

- name: Docker - Add user to docker group
  group:
    name: docker
    state: present

- name: Docker User
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop:
    - "{{ lookup('env','USER') }}"
    - ubuntu
