---
- name: Git-Filter-Repo Exists
  stat:
    path: /usr/local/bin/git_filter_repo.py
  register: git_filter_repo_exists_result

- block:
    - name: Git-Filter-Repo - Get latest
      community.general.github_release:
        user: newren
        repo: git-filter-repo
        action: latest_release
        token: "{{ github_token }}"
      register: git_filter_repo_latest_version
  when: git_filter_repo_exists_result.stat.exists == false or upgrade == true

# - name: Version
#   debug:
#     msg: "{{ git_filter_repo_latest_version }}"
- block:
    - name: Git-Filter-Repo - Install/Upgrade
      get_url:
        url: "https://github.com/newren/git-filter-repo/releases/download/{{ git_filter_repo_latest_version.tag }}/git-filter-repo-{{ git_filter_repo_latest_version.tag[1:] }}.tar.xz"
        dest: "/usr/local/git-filter-repo-{{ git_filter_repo_latest_version.tag }}"
        mode: 'u+x,g+x,o+x'
        force: true
  when: git_filter_repo_exists_result.stat.exists == false or upgrade == true


- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /usr/local/git-filter-repo-{{ git_filter_repo_latest_version.tag[1:] }}"
    dest: /usr/local/git-filter-repo
    remote_src: yes