---
# - name: GH - Get signing key
#   apt_key:
#     url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
#     state: present

# - name: GH - Add apt repository
#   apt_repository:
#     repo: "deb https://cli.github.com/packages stable main"
#     state: present
#     filename: gh

- name: GH - Install
  apt:
    pkg:
      - gh