---
- name: Golang - Exists
  stat:
    path: /usr/local
  register: golang_exists_result

- block:
    - name: Golang - Install/Upgrade
      unarchive:
        src: "{{ golang_url }}"
        dest: /usr/local
        remote_src: true
      # when: (golang_exists_result.stat.exists == "false") or (golang_installed_version != golang_latest_version)
  when:
    - (golang_exists_result.stat.exists == False) or (golang_exists_result.stat.exists != False and upgrade == True)
