---
- name: Golang - Exists
  stat:
    path: /usr/local/bin/go
  register: golang_exists_result

- block:
    - name: Golang - Install/Upgrade
      unarchive:
        src: "{{ golang_url }}"
        dest: /usr/local
        remote_src: yes
      when: (golang_exists_result.stat.exists == False) or (golang_installed_version != golang_latest_version)
  when:
    - (golang_exists_result.stat.exists == false) or (golang_exists_result.stat.exists != false and upgrade == true)
