---
- name: Gopass - Exists
  stat:
    path: /usr/local/bin/go
  register: gopass_exists_result

- block:
    - name: GoPass - Install/Upgrade
      shell: go install github.com/gopasspw/gopass@latest
  when:
    - (gopass_exists_result.stat.exists == False) or (gopass_exists_result.stat.exists != False and upgrade == True)


