---
- name: Granted - Exists
  ansible.builtin.stat:
    path: /usr/local/bin/granted
  register: granted_exists_result

- name: Granted - Install/Upgrade
  block:
    - name: Granted - Get latest
      community.general.github_release:
        user: common-fate
        repo: granted
        action: latest_release
        token: "{{ github_token }}"
      register: granted_latest_version

    - name: Granted - Set latest version
      set_fact:
        granted_latest_version: "{{ granted_latest_version.tag[1:] }}"

    - name: Granted - Install/Upgrade
      ansible.builtin.unarchive:
        src: "https://github.com/common-fate/granted/archive/refs/tags/v{{ granted_latest_version }}.tar.gz"
        dest: /usr/local/bin
        mode: 'u+x,g+x,o+x'
        remote_src: yes
  when: granted_exists_result.stat.exists == false or upgrade == true
