---
- name: Minikube Exists
  stat:
    path: /usr/local/bin/minikube
  register: minikube_exists_result

- block:
    - name: Minikube - Get installed version
      command: minikube version
      register: minikube_version_result

    - name: Minikube - Set found version
      set_fact:
        minikube_found_version: "{{ minikube_version_result.stdout_lines[0]| regex_search(regexp,'\\1') }}"
      vars:
        regexp: 'minikube\sversion:\s(.*)$'

    - name: Minikube - Set installed version
      set_fact:
        minikube_installed_version: "{{  minikube_found_version[0] }}"
  when: minikube_exists_result.stat.exists != false and upgrade == true

- block:
    - name: Minikube - Get latest
      community.general.github_release:
        user: kubernetes
        repo: minikube
        action: latest_release
        token: "{{ github_token }}"
      register: minikube_latest_version_result

    - name: Minikube - Set latest version
      set_fact:
        minikube_latest_version: "{{ minikube_latest_version_result.tag }}"

    - name: "Minikube - Version"
      debug:
        msg: "installed: {{ minikube_installed_version|default('N/A') }}, latest: {{ minikube_latest_version }}"
  when: minikube_exists_result.stat.exists != false and upgrade == true

- name: Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: 0755
    force: true
  when: >-
    (minikube_exists_result.stat.exists == false) or
    upgrade == true and
    (minikube_installed_version != minikube_latest_version)
