---
- name: mkcert - Exists
  stat:
    path: /usr/local/bin/mkcert
  register: mkcert_exists_result

- block:
    - name: mkcert - Get installed version
      command: mkcert --version
      register: mkcert_version_result

    - name: mkcert - Set installed version
      set_fact:
        mkcert_installed_version: "{{ mkcert_version_result.stdout }}"

    - name: "mkcert - Debug: Installed version"
      debug:
        msg: "{{ mkcert_installed_version }}"
      when: debug == true
  when: mkcert_exists_result.stat.exists != false and upgrade == true

- block:
    - name: mkcert - Get latest 
      community.general.github_release:
        user: FiloSottile 
        repo: mkcert
        action: latest_release
        token: "{{ github_token }}"
      register: mkcert_latest_version

    - name: mkcert - Set latest version
      set_fact:
        mkcert_latest_version: "{{ mkcert_latest_version.tag }}"

    - name: "mkcert - Debug:  Latest version"
      debug:
        msg: "{{ mkcert_latest_version }}"
      when: debug == true
  when: mkcert_exists_result.stat.exists == false or upgrade == true
  
- name: mkcert - Install/Upgrade
  get_url:
    url: "https://github.com/FiloSottile/mkcert/releases/download/{{ mkcert_latest_version }}/mkcert-{{ mkcert_latest_version }}-linux-amd64"
    dest: /usr/local/bin/mkcert
    mode: 'u+x,g+x,o+x'
    force: true
  when: (mkcert_exists_result.stat.exists == false) or upgrade == true and (mkcert_installed_version != mkcert_latest_version)
