
---
- name: 1Password - Install/Upgrade
  ansible.builtin.apt:
    deb: "{{ item }}"
    state: present
  loop:
    - https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
    - https://downloads.1password.com/linux/debian/amd64/stable/1password-cli-amd64-latest.deb
