---
- name: Terraform - Exists
  ansible.builtin.stat:
    path: /usr/local/bin/terraform
  register: terraform_exists_result

- name: Terraform Install/Upgrade
  block:
    - name: Terraform - Get latest
      community.general.github_release:
        user: hashicorp
        repo: terraform
        action: latest_release
        token: "{{ github_token }}"
      register: terraform_latest_version_result

    - name: Terraform - Set latest version
      ansible.builtin.set_fact:
        terraform_latest_version: "{{ terraform_latest_version_result.tag[1:] }}"

    - name: Terraform Install/Upgrade
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/terraform/{{ terraform_latest_version }}/terraform_{{ terraform_latest_version }}_linux_amd64.zip"
        dest: /usr/local/bin
        remote_src: true
  when: terraform_exists_result.stat.exists == false or upgrade == true
