---
- name: Vagrant Signing key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Vagrant Repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present

- name: Vagrant Install
  apt:
    pkg:
      - vagrant
