- name: Virtualbox - Exists
  stat:
    path: /usr/bin/teams
  register: virtualbox_exists_result

- block:
    - name: Virtualbox signing key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Virtualbox Repository
      apt:
        deb: "https://download.virtualbox.org/virtualbox/7.0.2/virtualbox-7.0_7.0.2-154219~Ubuntu~jammy_amd64.deb"
        state: present

    - name: Virtualbox Install
      apt:
        update_cache: true
        pkg:
          - virtualbox-7.0
  when: virtualbox_exists_result.stat.exists == false or upgrade == true
