---
- name: User
  debug:
    msg: "{{ ansible_user_id }}"

- name: Sudo User
  debug:
    msg: "{{ lookup('env','USER') }}"

- name: System
  debug:
    msg: "{{ ansible_system }}"

- name: Architecture
  debug:
    msg: "{{ ansible_userspace_architecture }}"

- name: Distribution
  debug:
    msg: "{{ ansible_distribution }}"

- name: Release
  debug:
    msg: "{{ ansible_distribution_release }}"
