---
- name: Add non-free official repository for Debian
  apt_repository:
    repo: "deb http://ftp.ca.debian.org/debian/ {{ ansible_distribution_release }} main non-free"
    state: present
  when: ansible_distribution == "Debian"

- name: Install system packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Install pip modules
  pip:
    name: "{{ pip_packages }}"
