---
- name: Add non-free official repository for Debian
  apt_repository:
    repo: "deb http://ftp.ca.debian.org/debian/ {{ ansible_distribution_release }} main non-free"
    state: present
  when: ansible_distribution == "Debian"

- name: Install system packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Install pip modules
  pip:
    name: "{{ pip_packages }}"

- name: Install collections
  community.general.ansible_galaxy_install:
    ack_ansible29: yes
    type: collection
    requirements_file: "{{ role_path }}/files/requirements.yml"
