---
- name: include os vars
  include_vars: "{{ ansible_distribution }}.yml"

- block:
    - import_tasks: debug.yml
    - import_tasks: deps.yml
    - import_tasks: module/aws-cli.yml
    - import_tasks: module/aws-vault.yml
    - import_tasks: module/dropbox.yml
    - import_tasks: module/github-cli.yml
    - import_tasks: module/gopass.yml
    - import_tasks: module/opass.yml
    - import_tasks: module/ssm-manager-plugin.yml
    - import_tasks: module/vscode.yml
  tags:
    - core

- import_tasks: module/act.yml
  tags:
    - act

- import_tasks: module/atlantis.yml
  tags:
    - atlantis

- import_tasks: module/docker.yml
  tags:
    - docker
    - docker-compose

- import_tasks: module/docker-compose.yml
  tags:
    - docker-compose

- import_tasks: module/git-filter-repo.yml
  tags:
    - git-filter-repo

- import_tasks: module/git-lfs.yml
  tags:
    - git-lfs

- import_tasks: module/kubectl.yml
  tags:
    - kubectl
    - minikube

- import_tasks: module/leapp.yml
  tags:
    - leapp

- import_tasks: module/minikube.yml
  tags:
    - minikube

- import_tasks: module/mkcert.yml
  tags:
    - mkcert

- import_tasks: module/ngrok.yml
  tags:
    - atlantis
    - ngrok

- import_tasks: module/packer.yml
  tags:
    - packer

- import_tasks: module/postman.yml
  tags:
    - postman

- import_tasks: module/skype.yml
  tags:
    - skype
    - comms

- import_tasks: module/slack.yml
  tags:
    - slack
    - comms

- import_tasks: module/teams.yml
  tags:
    - teams
    - comms

- import_tasks: module/teamviewer.yml
  tags:
    - comms
    - teamviewer

- import_tasks: module/terraform.yml
  tags:
    - terraform

- import_tasks: module/tor-browser.yml
  tags:
    - tor

- import_tasks: module/vagrant.yml
  tags:
    - virtualbox
    - vagrant

- import_tasks: module/virtualbox.yml
  tags:
    - virtualbox

- import_tasks: module/zoom.yml
  tags:
    - zoom
    - comms
