---
- name: include os vars
  include_vars: "{{ ansible_distribution }}.yml"

- import_tasks: debug.yml
  when: debug == True

- import_tasks: deps.yml
  tags:
    - all

- import_tasks: module/act.yml
  tags:
    - act

- import_tasks: module/atlantis.yml
  tags:
    - atlantis

- import_tasks: module/aws-cli.yml
  tags:
    - aws-cli
    - aws
    - req

- import_tasks: module/aws-vault.yml
  tags:
    - aws-vault
    - aws
    - req

- import_tasks: module/docker.yml
  tags:
    - docker
    - docker-compose
    - docker-machine

- import_tasks: module/docker-compose.yml
  tags:
    - docker-compose
    - req

- import_tasks: module/dropbox.yml
  tags:
    - dropbox

- import_tasks: module/git-filter-repo.yml
  tags:
    - git-filter-repo

- import_tasks: module/git-lfs.yml
  tags:
    - git-lfs

- import_tasks: module/github-cli.yml
  tags:
    - github-cli

- import_tasks: module/golang.yml
  tags:
    - golang
    - gopass

- import_tasks: module/gopass.yml
  tags:
    - golang

- import_tasks: module/kubectl.yml
  tags:
    - kubectl
    - minikube
    - req

- import_tasks: module/leapp.yml
  tags:
    - leapp
    - req

- import_tasks: module/minikube.yml
  tags:
    - minikube
    - req

- import_tasks: module/mkcert.yml
  tags:
    - mkcert

- import_tasks: module/ngrok.yml
  tags:
    - atlantis
    - ngrok

- import_tasks: module/packer.yml
  tags:
    - packer

- import_tasks: module/postman.yml
  tags:
    - postman

- import_tasks: module/skype.yml
  tags:
    - skype
    - comms

- import_tasks: module/slack.yml
  tags:
    - slack
    - comms

- import_tasks: module/ssm-manager-plugin.yml
  tags:
    - ssm-manager-plugin
    - req

- import_tasks: module/teams.yml
  tags:
    - teams
    - comms

- import_tasks: module/teamviewer.yml
  tags:
    - comms
    - teamviewer

- import_tasks: module/terraform.yml
  tags:
    - terraform
    - req

- import_tasks: module/tor-browser.yml
  tags:
    - tor

- import_tasks: module/vagrant.yml
  tags:
    - virtualbox

- import_tasks: module/virtualbox.yml
  tags:
    - virtualbox
    - vagrant

- import_tasks: module/vscode.yml
  tags:
    - vscode
    - req

- import_tasks: module/zoom.yml
  tags:
    - zoom
    - comms
    - req
