---
- name: AWS-Cli - Install
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /usr/local
    remote_src: true

- name: AWS-Cli - Configure
  command: sh /usr/local/aws/install --update