---
- name: Docker - Get signing key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Docker - Add apt repository
  apt_repository:
    update_cache: no
    repo: "deb [amd=64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    filename: docker

- name: Docker - Install
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Docker - Add docker group
  group:
    name: docker
    state: present

- name: Docker User
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop:
    - "{{ lookup('env','USER') }}"
