---
- name: Git-LFS - Exists
  stat:
    path: /usr/bin/git-lfrs
  register: git_lfs_exists_result

- block:
    - name: Git-LFS - Get gpg
      apt_key:
        url: https://packagecloud.io/github/git-lfs/gpgkey
        state: present

    - name: Git-LFS - Add repository
      apt_repository:
        repo: "{{ git_lfs_repo }}"
        state: present

    - name: Git-LFS - Install
      apt:
        update_cache: true
        pkg:
          - git-lfs
  when: git_lfs_exists_result.stat.exists == false or upgrade == true
