---
- name: Git-Filter-Repo Exists
  stat:
    path: /usr/local/bin/git_filter_repo.py
  register: git_filter_repo_exists_result


# - block:
#     - name: Git-Filter-Repo - Get installed version
#       command: aws-vault --version
#       register: aws_vault_version_result

#     - name: AWS-Vault - Set installed version
#       set_fact:
#         aws_vault_installed_version: "{{ aws_vault_version_result.stderr[1:] }}"
#   when: aws_vault_exists_result.stat.exists != false and upgrade == true


- block:
    - name: Git-Filter-Repo - Get latest
      community.general.github_release:
        user: newren
        repo: git-filter-repo
        action: latest_release
        token: "{{ github_token }}"
      register: git_filter_repo_latest_version_result

    - name: Git-Filter-Repo - Set latest version
      set_fact:
        git_filter_repo_latest_version: "{{ git_filter_repo_latest_version_result.tag }}"

    - name: Git-Filter-Repo - Version
      debug:
        msg: "installed: {{ git_filter_repo_installed_version|default('N/A') }}, latest: {{ git_filter_repo_latest_version }}"
  when: git_filter_repo_exists_result.stat.exists == false or upgrade == true

- block:
    - name: Git-Filter-Repo - Install/Upgrade
      ansible.builtin.unarchive:
        src: "https://github.com/newren/git-filter-repo/releases/download/{{ git_filter_repo_latest_version }}/git-filter-repo-{{ git_filter_repo_latest_version[1:] }}.tar.xz"
        dest: /usr/local
        mode: 'u+x,g+x,o+x'
        remote_src: yes

    - name: Git-Filter-Repo Configure
      file:
        src: /usr/local/git-filter-repo-{{ git_filter_repo_latest_version[1:] }}/git_filter_repo.py
        dest: /usr/local/bin/git-filter-repo
        state: link
  when: git_filter_repo_exists_result.stat.exists == false or upgrade == true

