---
- name: GH - Get signing key
  apt_key:
    url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
    state: present

- name: GH - Add apt repository
  apt_repository:
    repo: "deb https://cli.github.com/packages stable main"
    state: present
    filename: gh.list

- name: GH - Install
  apt:
    pkg:
      - gh

# - name: GitHub CLI - Exists
#   stat:
#     path: /usr/local/bin/gh
#   register: gh_exists_result

# - block:
#     - name: GitHub CLI - Get latest
#       community.general.github_release:
#         user: cli
#         repo: cli
#         action: latest_release
#         token: "{{ github_token }}"
#       register: gh_latest_version
#   when: gh_exists_result.stat.exists == False or upgrade == True

# - name: GitHub CLI - Version
#   debug:
#     msg: "{{ gh_latest_version }}"

# - block:
#     - name: GitHub CLI - Install/Upgrade
#       get_url:
#         url: "https://github.com/cli/cli/releases/download/{{ gh_latest_version.tag }}/gh_{{ gh_latest_version.tag[1:] }}_linux_amd64.tar.gz"
#         dest: /tmp/
#         mode: 'u+x,g+x,o+x'
#         force: true
#   when: gh_exists_result.stat.exists == False or upgrade == True

# - name: Unarchive a file that is already on the remote machine
#   ansible.builtin.unarchive:
#     src: "/tmp/gh_{{ gh_latest_version.tag[1:] }}_linux_amd64.tar.gz"
#     dest: /usr/local
#     remote_src: yes