- name: Leapp Exists
  stat:
    path: /usr/bin/leapp
  register: leapp_exists_result

- name: Leapp Install
  apt:
    deb: "https://asset.noovolari.com/latest/Leapp_{{ leapp_version }}_amd64.deb"
  when: leapp_exists_result.stat.exists == false or upgrade == true