---
- name: Create a temporary directory
  tempfile:
    state: directory
    suffix: tmp
  register: tmpdir

- name: Minikube Exists
  stat:
    path: /usr/local/bin/minikube
  register: minikube_exists_result

- name: Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: 0755
    force: true
  when: minikube_exists_result.stat.exists == False or upgrade == True