---
- name: Ngrok - Exists
  stat:
    path: /usr/local/bin/ngrok
  register: ngrok_exists_result

- block:
    - name: Ngrok - Get installed version
      command: ngrok --version
      register: ngrok_version_result
      ignore_errors: true

    - name: Ngrok - Set installed version
      set_fact:
        ngrok_installed_version: "{{ ngrok_version_result.stdout | regex_search(regexp,'\\1') }}"
      vars:
        regexp: '^ngrok version (.*)$'

    - name: "Ngrok - Version"
      debug:
        msg: "{{ ngrok_installed_version }}"
      when: debug == "true"
  when: ngrok_exists_result.stat.exists != false and upgrade == true

- name: Ngrok Install/Upgrade
  unarchive:
    src: "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip"
    dest: /usr/local/bin
    remote_src: true
  when: ngrok_exists_result.stat.exists == false or upgrade == true
