---
- name: One Pass - Exists
  stat:
    path: /usr/bin/1password
  register: op_exists_result

- name: One Pass - Install/Upgrade
  apt:
    deb: "{{ item }}"
    state: present
  loop:
    - https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
    - https://downloads.1password.com/linux/debian/amd64/stable/1password-cli-amd64-latest.deb