---
- name: Slack - Exists
  stat:
    path: /usr/bin/slack
  register: slack_exists_result

- name: Slack
  community.general.snap:
    name: slack
    classic: true
  when: slack_exists_result.stat.exists == false or upgrade == true